### ISSUE TITLE
そろそろファイル分けませんか

### ISSUE THREAD

**Issue by bgpat** [kstm-su/omotenashi#2]
全部test.jsxに書いてるとどこかでコンフリクトしそうな気がして…

**Comment by u63** [comment]
すでに起こってるね。まだ直せる範囲だからいいけど。

**Comment by Goryudyuma** [comment]
まだ手で直せる範囲ではあるけど、すでにコンフリクトしてるよ。

そろそろ分けたいね。

**Comment by bgpat** [comment]
分け終わってたので閉じます
